Contoso/Contoso.Web/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contoso.Service;
using Contoso.Model;

namespace Contoso.Web.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course

        protected ICourseService _CourseService;
        public CourseController(ICourseService courseService)
        {
            this._CourseService = courseService;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllCourses()
        {
            var allcourses = _CourseService.GetAll();
            return View(allcourses);
        }


        public ActionResult GetById(int id)
        {
            var CourseById = _CourseService.GetById(id);
            return View(CourseById);
        }
    }
}

Contoso/Contoso.Web/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contoso.Service;
using Contoso.Model;
using Contoso.Web.Filter;

namespace Contoso.Web.Controllers
{
    //[HandleError]
    [ContosoExceptionFilter]
    public class DepartmentController : Controller
    {
        // GET: Department
        private readonly IDepartmentService _departmentservice;
        public DepartmentController(IDepartmentService departmentService)
        {
            this._departmentservice = departmentService;
        }

        
        public ActionResult Index()
        {

            //int i = 0; int x = 1;
            //int y = x / i;
            var departments = _departmentservice.GetAllDepartments();
            //ViewData["depts"] = departments;
            ViewBag.DepartmentCount = departments.Count();
            return View(departments); // return view in same folder with same name;

        }

        public ActionResult Max()
        {
            //var maxbudget = _departmentservice.GetMaxValue();
            //ViewBag.Max = maxbudget;
            return View();
        }


        public ActionResult ById()
        {

            //return View(departmentbyid);
            int id = Convert.ToInt32(Request.Form["Id"]);
            //var departmentbyname = _departmentservice.GetById(id);
            //return View(departmentbyname);
            return View();
        }

        //public ActionResult ByName()
        //{
        //    string name = Request.Form["Name"];
        //    var departmentbyname = _departmentservice.GetByName(name);
        //    return View(departmentbyname);
        //}


        [HttpPost]
        public ActionResult ByName()
        {
            string name = Request.Form["Name"];
            //return View();
            var departmentbyname = _departmentservice.GetDepartByName(name);
            return View(departmentbyname);
            
        }

        [HttpGet]
        [ActionName("ByName")]
        public ActionResult GetByName()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddValue()
        {
            Depart department = new Depart();
            department.Name = Request.Form["Name"];
            department.Budget = Convert.ToDecimal(Request.Form["Budget"]);
            department.StartDate = Convert.ToDateTime(Request.Form["StartDate"]);
            department.InstructorId = Convert.ToInt32(Request.Form["InstructorId"]);
            department.RowVersion = Request.Form["RowVersion"];
            //_departmentservice.AddDepartment(department);
            return View();
        }
        [HttpGet]
        [ActionName("AddValue")]
        public ActionResult GetAddValue()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create2()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create2(Depart department)
        {
            //Get the data from formcollection and call service layer 
            //save to database
            //try
            //{
            //    var departname = form["departname"];
            //    var budget = form["budget"];
            //    var startdate = form["startdate"];

            //    Depart department = new Depart();
            //    department.Name = departname;
            //    department.Budget = Convert.ToDecimal(budget);
            //    department.StartDate = Convert.ToDateTime(startdate);
            //    department.InstructorId = 1;

            //    _departmentservice.AddDepartment(department);

            //    return RedirectToAction("Index");
            //}
            //catch (Exception)
            //{

            //    return View();
            //}
            try
            {
                department.InstructorId = 1;

                //_departmentservice.AddDepartment(department);

                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var department = _departmentservice.GetDepartmentById(id);
            return View(department);
        }
        [HttpPost]
        public ActionResult Edit(Depart department)
        {
            //_departmentservice.UpdateDepartment(department);

            return RedirectToAction("Index");
        }
    }
}  

Contoso/Contoso.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Contoso.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Contoso/Contoso.Web/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Contoso.Service;
using Contoso.Model;

namespace Contoso.Web.Controllers
{
    public class PeopleController : Controller
    {
        // GET: People
        private IPeopleService _peopleService;

        public PeopleController(IPeopleService peopleService)
        {
            this._peopleService = peopleService;
        }
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllPeople()
        {
            var result = _peopleService.GetAllPeople();
            return View(result);
        }

        

        public ActionResult GetByFirstName()
        {
            string name = Request.Form["FirstName"];
            var result = _peopleService.GetByFirstName(name);
            return View(result);
        }

    }
}

Contoso/Contoso.Web/Views/Course/AddCourse.cshtml
@model Contoso.Model.Course

@{
    ViewBag.Title = "AddCourse";
}

<h2>AddCourse</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contoso/Contoso.Web/Views/Course/GetAllCourses.cshtml
@model IEnumerable<Contoso.Model.Course>

@{
    ViewBag.Title = "GetAllCourses";
}

<h2>GetAllCourses</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Credits)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Credits)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedBy)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Contoso/Contoso.Web/Views/Course/GetById.cshtml
@model Contoso.Model.Course
@{
    ViewBag.Title = "GetById";
}

<h2>GetById</h2>
<table class="table table-hover">
    <tr>
        <td>Id</td>
        <td>Title</td>
        <td>Instructor</td>
    </tr>
    <tr>
        <td>@Model.Id</td>
        <td>@Model.Title</td>
        <td>@Model.DepartId</td>
    </tr>
</table>

Contoso/Contoso.Web/Views/Course/UpdateCourse.cshtml
@model Contoso.Model.Course

@{
    ViewBag.Title = "UpdateCourse";
}

<h2>UpdateCourse</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Credits, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credits, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credits, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contoso/Contoso.Web/Views/Department/AddValue.cshtml
@model Contoso.Model.Depart
@{
    ViewBag.Title = "AddValue";
}

<body>
    <div>
        @using (Html.BeginForm("AddValue", "Department", FormMethod.Post))
        {
            @*<p>Plz Enter Department Id</p>
            @Html.TextBox("Id");*@
            <p>Plz Enter Department Name</p>
            @Html.TextBox("Name");
            <p>Plz Enter Department Budget</p>
            @Html.TextBox("Budget");
            <p>Plz Enter Department StartDate</p>
            @Html.TextBox("StartDate");
            <p>Plz Enter Department InstructorId</p>
            @Html.TextBox("InstructorId");
            <p>Plz Enter Department Rowversion</p>
            @Html.TextBox("RowVersion");
            <input type="submit" value="submit" />
        }
    </div>
</body>


Contoso/Contoso.Web/Views/Department/ById.cshtml
@model Contoso.Model.Depart
@{
    ViewBag.Title = "ById";
}

<body>
    <div>
        @using (Html.BeginForm("ById", "Department", FormMethod.Post))
        {
            @Html.TextBox("Id");
            <input type="submit" value="submit" />
        }
    </div>
    <hr/>
    <br />
    @if(Model != null) { 
    <table class="table">
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Budget</td>
        </tr>
    </table>
    }
    
</body>

Contoso/Contoso.Web/Views/Department/ByName.cshtml
@model Contoso.Model.Depart
@{
    ViewBag.Title = "ByName";
}

<body>
    <div>
        @using (Html.BeginForm("ByName", "Department", FormMethod.Post))
        {
            @Html.TextBox("Name");
            <input type="submit" value="submit" />
        }
    </div>
    <hr />
    <br />
    @if (Model != null) {
    <table class="table">
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Budget</td>
        </tr>
    </table>
    }
    
</body>

Contoso/Contoso.Web/Views/Department/Create.cshtml
@model Contoso.Model.Depart

@{
    ViewBag.Title = "Create";
}
@*Razor View*@
<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Depart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstructorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstructorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RowVersion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RowVersion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RowVersion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contoso/Contoso.Web/Views/Department/Create2.cshtml

@{
    ViewBag.Title = "Create2";
}

<h2>Create</h2>
<form method="post">
    Name <input type="text" name="Name" value="" />
    <br />
    Budget <input type="number" name="Budget" value="" />
    <br />
    StartDate <input type="date" name="Startdate" value="" />
    <br />
    <input type="submit" name="savedepartment" value="save" class="btn btn-primary"/>
</form>

Contoso/Contoso.Web/Views/Department/Edit.cshtml
@model Contoso.Model.Depart

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Depart</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.DropDownList(model)*@
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.InstructorId, new SelectList((IEnumerable<Contoso.Model.Instructor>)Model.Instructors, "Id", "Name"), "Select");
                @Html.EditorFor(model => model.InstructorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstructorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RowVersion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RowVersion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RowVersion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Contoso/Contoso.Web/Views/Department/Index.cshtml
@model List<Contoso.Model.Depart>

@{
    ViewBag.Title = "Index";
}


<h2>Total Departments: @ViewBag.DepartmentCount</h2>
<table class="table table-striped table-dark">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Budget</td>
        <td>StartDate</td>
    </tr>
    @foreach (var department in Model)
    {
        <tr>
            <td>@department.Id</td>
            <td>@department.Name</td>
            <td>@department.Budget</td>
            <td>@department.StartDate</td>


        </tr>
    }
</table>



Contoso/Contoso.Web/Views/Department/Max.cshtml

@{
    ViewBag.Title = "Max";
}

<h2>Max budget is:@ViewBag.Max</h2>



Contoso/Contoso.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Contoso/Contoso.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Contoso/Contoso.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Contoso/Contoso.Web/Views/People/GetByFirstName.cshtml
@model Contoso.Model.People
@{
    ViewBag.Title = "GetByFirstName";
}

<h2>GetByFirstName</h2>
<hr />
<br />
<table>
    @using (Html.BeginForm("GetByFirstName", "People", FormMethod.Post)) { 
    <tr>
        <td>
            @Html.TextBox("FirstName")
        </td>
        <td>
            <input type="submit" value="submit" />
        </td>
    </tr>
    }
</table>
<hr />
<br />
<table class="table table-danger">
    @if(Model != null)
    {
        <tr>
            <td>@Model.Id</td>
            <td>@Model.FirstName</td>
            <td>@Model.LastName</td>
        </tr>
    }
</table>


Contoso/Contoso.Web/Views/People/Index.cshtml
@model List<Contoso.Model.People>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<body>
    <table class="table table-dark">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.FirstName</td>
                <td>@item.LastName</td>
                <td>@item.DateOfBirth</td>
            </tr>
        }
    </table>
</body>

Contoso/Contoso.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>